version: '3'

services: #containers

  ########################### PHP ###########

  php_comparison:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: php_comparison
    volumes:
      - ./:/var/www/html/comparison
      - ./docker/xdebug/90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini
    working_dir: /var/www/html/comparison
    networks:
      - comparison_network

  ########### SERVER ########################
  #
  nginx_comparison:
    image: nginx:latest
    container_name: nginx_comparison
    ports:
      - "8002:80"
    volumes:
      - ./:/var/www/html/comparison
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - comparison_network
    expose:
      - 8083

  ############################## Data Base ###########
  postgresql_comparison:
    build:
      context: ./docker/db_config
      dockerfile: Dockerfile
    container_name: postgresql_comparison
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comparison_db
    restart: unless-stopped
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data
    tty: true
    networks:
      - comparison_network
    expose:
      - 5432


  ################## ARTISAN ##############

  artisan_comparison:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: artisan_comparison
    volumes:
      - ./:/var/www/html/comparison
    depends_on:
      - postgresql_comparison
    working_dir: /var/www/html/comparison
    entrypoint: ["php", "artisan"]
    command: ["queue:work"]
    restart: always
    networks:
      - comparison_network

  ############### redis ###########################

  redis_comparison:
    image: 'redis:alpine'
    container_name: redis_comparison
    ports:
      - "6390:6379"
    restart: unless-stopped
    networks:
      - comparison_network
    expose:
      - 6390


  ################# ES
  elasticsearch_comparison:
    image: 'elasticsearch:8.9.1'
    container_name: elasticsearch_comparison
    ports:
      - "9200:9200"
      - "9301:9301"
    environment:
      - "discovery.type=single-node"  # This line sets Elasticsearch to single-node mode
      - "xpack.security.enabled=false" # Disable X-Pack (including security features)
    networks:
      - comparison_network
    volumes:
      - ./docker/es_data:/usr/share/elasticsearch/data
    expose:
      - 9200
      - 9301
  ################### RabbitMQ
#  rabbitmq_comparison:
#    build:
#      context: ./docker/rabbitmq
#      dockerfile: Dockerfile
#    hostname: "rabbitmq"
#    container_name: rabbitmq_comparison
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - comparison_network
#    volumes:
#      - ./docker/rabbitmq/persistence/data/:/var/lib/rabbitmq/
#      - ./docker/rabbitmq/persistence/log/:/var/log/rabbitmq

  ################## COMMAND to consumer rabbitmq msg ##############

#  comparison_rabbitmq_consumer:
#    build:
#      context: ./docker/php
#      dockerfile: Dockerfile
#    container_name: comparison_rabbitmq_consumer
#    volumes:
#      - ./:/var/www/html/comparison
#    depends_on:
#      - postgresql_comparison
#      - composer_comparison
#    working_dir: /var/www/html/comparison
#    entrypoint: ["php", "artisan"]
#    command: ["start_rabbitmq"]
#    restart: always
#    networks:
#      - comparison_network


networks:
  comparison_network:
    external: true
